### ISSUE TITLE
Sauce Labs: Status missed for `perTest` and `refreshClient`

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/rowdy#22]
Need additional status setting in the following situations:

* Config specifies `perTest: true`. Need status after each test.
* Code call to `adapter.refreshClient()`. Need status after each call (this may be weird to set).

**UPDATE**: On thinking through this more, the most correct plan of action is probably:

1. Move all tracking of number of tests attempted / passed / failed _into_ the client.
2. Flush that state and reset whenever a client is destroyed _and_ do the sauce upload then.

**Comment by ryan-roemer** [comment]
@Maciek416 -- Just as a head's up, my guess is you'll want this bug resolved for eventual use in Sauce Labs land. It's not an issue currently if only one client (corresponding to a SL) session is spawned during a test, but is otherwise currently...

**Comment by Maciek416** [comment]
Is this is to update sauce itself on success/failure?

**Comment by ryan-roemer** [comment]
Yes. Currently, if you set the adapter to spawn a new client on each test (`beforeEach` instead of `before` -- the "upload to sauce" status is lost). 

There is a separate issue with doing per test client in that you're incurring a new SL session _every test_... But we _could_ update status as an aggregating "they all pass at this point for all the clients I've seen so far" type thing...
